project:
  type: website
  output-dir: _site


website:
  #title: "Automated Knitting Machine"
  navbar:
    background: "#f8dfe5"
    foreground: "#4a4a4a"
    left:
      - text: "Home"
        href: index.qmd

      - text: "User Guide"
        menu:
          - text: "Pattern Editor"
            href: pattern-editor.qmd
          - text: "Operating the Machine"
            href: operating-machine.qmd

      - text: "Control System"
        menu:
          - text: "System Overview"
            href: control-system.qmd
          - text: "Display Interface — GFX HAT"
            href: display-interface.qmd
          - text: "Raspberry Pi Application"
            href: raspberry-control.qmd
          - text: "ESP32 and Actuation"
            href: esp32-actuation.qmd
          - text: "Stepper Motor"
            href: stepper-motor.qmd
          - text: "Wiring and Power Supply"
            href: wiring-power.qmd
          - text: "Troubleshooting"
            href: troubleshooting.qmd

      - text: "Mechanical Design"
        menu:
          - text: "Components Overview"
            href: components.qmd
          - text: "3D-Printed Servo Arms"
            href: servo-arms.qmd
          - text: "3D Camera Mount"
            href: error-mount.qmd

      - text: "Error Recognition"
        menu:
          - text: "Overview"
            href: error-recognition.qmd
          - text: "Acquisition System"
            href: error-camera.qmd
          - text: "3D Camera Mount"
            href: error-mount.qmd
          - text: "Algorithm and Code"
            href: error-code.qmd
          - text: "Results and Efficiency"
            href: error-results.qmd
          - text: "Conclusions and Future Works"
            href: error-future_work.qmd

      - text: "Future Developments"
        href: future-developments.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    toc-depth: 4
    page-layout: full
